version: "3"

services:
  node:
    image: node:16
    container_name: talker_manager
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app/backend
    volumes:
      - ./:/app/backend
    ports:
      - 3000:3000

networks:
  default:
    name: talker_manager_net


